name: Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Configure Poetry
      run: |
        poetry config http-basic.azure <username> <password>
        poetry config repositories.azure https://pkgs.dev.azure.com/workbench-io/_packaging/workbench-io/pypi/upload/
      env:
        <username>: ${{ secrets.AZURE_DEVOPS_USERNAME }}
        <password>: ${{ secrets.AZURE_DEVOPS_PAT }}

    - name: Build and Publish
      run: |
        poetry build
        poetry publish -r azure
